Skills = [
    "Electronics maintenance",
    "Mechanical maintenance",
    "Optics handling",
    "Software operation",    
    "Instrument calibration",
    "Data acquisition",
    "Computing support",
    "Adaptive optics",
    "Cryogenics",
    "Network infrastructure", 
    "Instrument integration", 
    "Preventive maintenance",
    "Environment monitoring",
    "Technical reporting", 
    "Management"
]

Days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
T = range(len(Days))

# Tasks to be completed (duration is in hours)
Tasks = [
    {'title': 'Electronics diagnostics and repair', 'skill': 0, 'staff': 2, 'duration': 1, 'day': 0 },
    {'title': 'Real-time fault troubleshooting', 'skill': 0, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Assembly and testing of mechanical fixtures', 'skill': 1, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 2, 'day': 0 },
    {'title': 'Mentoring junior staff', 'skill': 14, 'staff': 1, 'duration': 3, 'day': 0 },
    {'title': 'IT and network maintenance', 'skill': 9, 'staff': 2, 'duration': 4, 'day': 0 },
    {'title': 'Updating and reviewing system logs', 'skill': 13, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 2, 'duration': 8, 'day': 0 },
    {'title': 'Instrument calibration', 'skill': 4, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Motorized component adjustments', 'skill': 1, 'staff': 1, 'duration': 2, 'day': 0 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 1, 'day': 0 },
    {'title': 'Optical alignment checks', 'skill': 2, 'staff': 2, 'duration': 3, 'day': 0 },
    {'title': 'Safety tests (interlocks and motion limits)', 'skill': 11, 'staff': 1, 'duration': 3, 'day': 0 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 3, 'day': 0 },
    {'title': 'Adaptive optics system validation', 'skill': 7, 'staff': 1, 'duration': 2, 'day': 0 },
    {'title': 'Documenting issues and proposed improvements', 'skill': 13, 'staff': 1, 'duration': 4, 'day': 0 },
    {'title': 'Assisting astronomers with instrument setups', 'skill': 14, 'staff': 1, 'duration': 4, 'day': 0 },
    {'title': 'Hardware installation and integration', 'skill': 10, 'staff': 2, 'duration': 5, 'day': 0 },
    {'title': 'Testing remote‑observing systems', 'skill': 6, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Preventive maintenance on control systems', 'skill': 11, 'staff': 1, 'duration': 3, 'day': 0 },
    {'title': 'Cryogenic system checks', 'skill': 8, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Sensor and actuator testing', 'skill': 0, 'staff': 1, 'duration': 2, 'day': 0 },
    {'title': 'Cleaning optical components', 'skill': 2, 'staff': 2, 'duration': 4, 'day': 0 },
    {'title': 'Facility maintenance (HVAC, water, power)', 'skill': 1, 'staff': 2, 'duration': 2, 'day': 0 },
    {'title': 'Preventive maintenance on control systems', 'skill': 11, 'staff': 2, 'duration': 3, 'day': 1 },
    {'title': 'Instrument calibration', 'skill': 4, 'staff': 1, 'duration': 2, 'day': 1 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 2, 'duration': 6, 'day': 1 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Sensor and actuator testing', 'skill': 0, 'staff': 1, 'duration': 2, 'day': 1 },
    {'title': 'Electronics diagnostics and repair', 'skill': 0, 'staff': 2, 'duration': 2, 'day': 1 },
    {'title': 'Drives and dome troubleshooting', 'skill': 1, 'staff': 2, 'duration': 2, 'day': 1 },
    {'title': 'Motorized component adjustments', 'skill': 1, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Hardware installation and integration', 'skill': 10, 'staff': 3, 'duration': 5, 'day': 1 },
    {'title': 'Real-time fault troubleshooting', 'skill': 0, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 2, 'day': 1 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Adaptive optics system validation', 'skill': 7, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Cryogenic system checks', 'skill': 8, 'staff': 2, 'duration': 2, 'day': 1 },
    {'title': 'Facility maintenance (HVAC, water, power)', 'skill': 1, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Documenting issues and proposed improvements', 'skill': 13, 'staff': 1, 'duration': 3, 'day': 1 },
    {'title': 'Testing weather‑monitoring systems', 'skill': 12, 'staff': 2, 'duration': 2, 'day': 1 },
    {'title': 'Optical alignment checks', 'skill': 2, 'staff': 1, 'duration': 1, 'day': 1 },
    {'title': 'IT and network maintenance', 'skill': 9, 'staff': 2, 'duration': 2, 'day': 1 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 2, 'day': 2 },
    {'title': 'Electronics diagnostics and repair', 'skill': 0, 'staff': 2, 'duration': 2, 'day': 2 },
    {'title': 'Software updates and testing', 'skill': 6, 'staff': 1, 'duration': 3, 'day': 2 },
    {'title': 'Structural and mechanical repairs', 'skill': 1, 'staff': 2, 'duration': 3, 'day': 2 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 2, 'day': 2 },
    {'title': 'Cryogenic system checks', 'skill': 8, 'staff': 2, 'duration': 2, 'day': 2 },
    {'title': 'Mentoring junior staff', 'skill': 14, 'staff': 1, 'duration': 2, 'day': 2 },
    {'title': 'Assembly and testing of mechanical fixtures', 'skill': 1, 'staff': 2, 'duration': 2, 'day': 2 },
    {'title': 'Testing remote‑observing systems', 'skill': 6, 'staff': 2, 'duration': 1, 'day': 2 },
    {'title': 'Instrument calibration', 'skill': 4, 'staff': 2, 'duration': 2, 'day': 2 },
    {'title': 'Testing weather‑monitoring systems', 'skill': 12, 'staff': 1, 'duration': 3, 'day': 2 },
    {'title': 'Thermal management of dome and telescope', 'skill': 12, 'staff': 1, 'duration': 2, 'day': 2 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 1, 'duration': 6, 'day': 2 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 3, 'day': 2 },
    {'title': 'Coordinating instrument upgrades', 'skill': 14, 'staff': 1, 'duration': 4, 'day': 2 },
    {'title': 'Drives and dome troubleshooting', 'skill': 1, 'staff': 2, 'duration': 2, 'day': 3 },
    {'title': 'Adaptive optics system validation', 'skill': 7, 'staff': 1, 'duration': 2, 'day': 3 },
    {'title': 'Assisting astronomers with instrument setups', 'skill': 14, 'staff': 1, 'duration': 2, 'day': 3 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 1, 'day': 3 },
    {'title': 'IT and network maintenance', 'skill': 9, 'staff': 1, 'duration': 3, 'day': 3 },
    {'title': 'Mentoring junior staff', 'skill': 14, 'staff': 1, 'duration': 2, 'day': 3 },
    {'title': 'Cryogenic system checks', 'skill': 8, 'staff': 2, 'duration': 2, 'day': 3 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 1, 'day': 3 },
    {'title': 'Electronics diagnostics and repair', 'skill': 0, 'staff': 1, 'duration': 3, 'day': 3 },
    {'title': 'Real-time fault troubleshooting', 'skill': 0, 'staff': 2, 'duration': 2, 'day': 3 },
    {'title': 'Instrument calibration', 'skill': 4, 'staff': 2, 'duration': 3, 'day': 3 },
    {'title': 'Safety tests (interlocks and motion limits)', 'skill': 11, 'staff': 1, 'duration': 3, 'day': 3 },
    {'title': 'Testing weather‑monitoring systems', 'skill': 12, 'staff': 2, 'duration': 1, 'day': 3 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 2, 'duration': 7, 'day': 3 },
    {'title': 'Optical alignment checks', 'skill': 2, 'staff': 2, 'duration': 3, 'day': 3 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 2, 'day': 3 },
    {'title': 'Documenting issues and proposed improvements', 'skill': 13, 'staff': 1, 'duration': 3, 'day': 3 },
    {'title': 'Assembly and testing of mechanical fixtures', 'skill': 1, 'staff': 1, 'duration': 1, 'day': 3 },
    {'title': 'Updating and reviewing system logs', 'skill': 13, 'staff': 1, 'duration': 2, 'day': 4 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 2, 'day': 4 },
    {'title': 'Motorized component adjustments', 'skill': 1, 'staff': 1, 'duration': 1, 'day': 4 },
    {'title': 'Documenting issues and proposed improvements', 'skill': 13, 'staff': 1, 'duration': 3, 'day': 4 },
    {'title': 'Electronics diagnostics and repair', 'skill': 0, 'staff': 1, 'duration': 3, 'day': 4 },
    {'title': 'Assembly and testing of mechanical fixtures', 'skill': 1, 'staff': 2, 'duration': 3, 'day': 4 },
    {'title': 'Instrument calibration', 'skill': 4, 'staff': 2, 'duration': 3, 'day': 4 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 2, 'day': 4 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 3, 'day': 4 },
    {'title': 'IT and network maintenance', 'skill': 9, 'staff': 2, 'duration': 3, 'day': 4 },
    {'title': 'Safety tests (interlocks and motion limits)', 'skill': 11, 'staff': 1, 'duration': 2, 'day': 4 },
    {'title': 'Real-time fault troubleshooting', 'skill': 0, 'staff': 1, 'duration': 1, 'day': 4 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 2, 'duration': 6, 'day': 4 },
    {'title': 'Testing weather‑monitoring systems', 'skill': 12, 'staff': 2, 'duration': 2, 'day': 4 },
    {'title': 'Structural and mechanical repairs', 'skill': 1, 'staff': 3, 'duration': 4, 'day': 4 },
    {'title': 'Thermal management of dome and telescope', 'skill': 12, 'staff': 1, 'duration': 3, 'day': 4 },
    {'title': 'Drives and dome troubleshooting', 'skill': 1, 'staff': 2, 'duration': 2, 'day': 5 },
    {'title': 'Thermal management of dome and telescope', 'skill': 12, 'staff': 1, 'duration': 3, 'day': 5 },
    {'title': 'Cryogenic system checks', 'skill': 8, 'staff': 1, 'duration': 3, 'day': 5 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 2, 'day': 5 },
    {'title': 'Documenting issues and proposed improvements', 'skill': 13, 'staff': 1, 'duration': 3, 'day': 5 },
    {'title': 'Cleaning optical components', 'skill': 2, 'staff': 1, 'duration': 3, 'day': 5 },
    {'title': 'Mentoring junior staff', 'skill': 14, 'staff': 1, 'duration': 2, 'day': 5 },
    {'title': 'Assisting astronomers with instrument setups', 'skill': 14, 'staff': 1, 'duration': 4, 'day': 5 },
    {'title': 'Testing remote‑observing systems', 'skill': 6, 'staff': 2, 'duration': 1, 'day': 5 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 1, 'duration': 6, 'day': 5 },
    {'title': 'Optical alignment checks', 'skill': 2, 'staff': 2, 'duration': 2, 'day': 5 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 2, 'day': 5 },
    {'title': 'Instrument calibration', 'skill': 4, 'staff': 2, 'duration': 3, 'day': 5 },
    {'title': 'Preventive maintenance on control systems', 'skill': 11, 'staff': 1, 'duration': 2, 'day': 5 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 2, 'day': 5 },
    {'title': 'Assisting astronomers with instrument setups', 'skill': 14, 'staff': 1, 'duration': 3, 'day': 6 },
    {'title': 'Monitoring weather and system status', 'skill': 12, 'staff': 1, 'duration': 3, 'day': 6 },
    {'title': 'Preparing dome and telescope for night operations', 'skill': 3, 'staff': 1, 'duration': 3, 'day': 6 },
    {'title': 'Nightly telescope operation', 'skill': 3, 'staff': 1, 'duration': 7, 'day': 6 },
    {'title': 'Documenting issues and proposed improvements', 'skill': 13, 'staff': 1, 'duration': 4, 'day': 6 },
    {'title': 'Real-time fault troubleshooting', 'skill': 0, 'staff': 1, 'duration': 2, 'day': 6 },
    {'title': 'Electronics diagnostics and repair', 'skill': 0, 'staff': 1, 'duration': 2, 'day': 6 },
    {'title': 'Mentoring junior staff', 'skill': 14, 'staff': 1, 'duration': 2, 'day': 6 },
    {'title': 'Instrument data-acquisition monitoring', 'skill': 5, 'staff': 1, 'duration': 2, 'day': 6 },
    {'title': 'Safety tests (interlocks and motion limits)', 'skill': 11, 'staff': 1, 'duration': 1, 'day': 6 },
    {'title': 'Software updates and testing', 'skill': 6, 'staff': 1, 'duration': 4, 'day': 6 }
]

# Skill scores for each staff member
Staff = [
    [19.0,14.8,5.8,0,2.6,7.3,5.9,0,23.6,5.9,0,6.3,1.1,15.3,1.2],
    [11.4,6.6,5.0,7.8,1.9,18.6,14.9,1.7,6.1,9.1,2.4,7.6,2.6,0,12.0],
    [0,11.7,7.9,6.4,10.9,1.6,5.4,15.9,6.9,9.6,3.5,9.4,6.8,0,14.6],
    [0,11.8,5.0,7.8,2.7,2.8,1.1,13.5,6.1,18.0,11.0,9.7,2.7,6.8,6.8],
    [6.2,3.9,0,1.3,26.7,2.1,14.8,0,2.9,2.7,11.3,13.7,0,6.6,18.4],
    [2.4,6.6,10.0,10.1,9.7,1.6,5.8,7.9,1.0,5.7,14.1,11.6,5.1,0,9.6],
    [3.1,7.2,7.6,7.8,11.3,6.9,23.5,13.9,0,1.2,3.8,6.5,13.8,1.2,3.8],
    [3.5,5.9,0,9.3,1.1,0,23.8,9.9,13.3,7.1,10.5,0,12.0,1.2,9.4],
    [1.5,7.6,17.5,3.3,0,2.5,5.0,11.5,9.4,17.1,7.2,0,10.6,3.9,11.3],
    [14.1,3.3,0,21.7,10.0,10.9,0,9.3,2.8,13.5,1.1,0,6.0,2.7,11.0],
    [1.2,6.7,11.9,7.3,6.0,1.1,1.1,6.8,5.2,5.9,7.0,7.5,11.1,15.6,10.1],
    [0,2.5,3.0,13.6,10.0,1.6,1.1,9.9,7.5,13.6,9.5,5.3,11.7,10.7,1.4],
    [1.7,15.6,11.7,5.6,10.3,3.4,9.8,5.4,1.0,0,10.3,2.2,7.1,1.7,18.3]
]

S = range(len(Skills))
J = range(len(Tasks))
I = range(len(Staff))

